sidebar:
  emoji: 🍥
  subtitle: Mes expériences de tiramisu à Paris et ailleurs.
  compact: true
  avatar:
    enabled: true
    local: true
    src: img/tiravatar.jpg

#DateFormat:
#  published: 02 January 2006
#  lastUpdated: 02 January 2006 13:12

article:
  license:
    enabled: true
    default: Tous droits réservés

footer:
  since: 2024
  customText: TiraMissJu Blog by JuliaLblnd

widgets:
  homepage:
#    - type: search
#    - type: archives
#      params:
#        limit: 5
    - type: categories
      params:
        limit: 10
    - type: tag-cloud
      params:
        limit: 10
