baseURL = 'https://julialblnd.github.io/TiraMissJuBlog'
languageCode = 'fr-fr'
title = 'TiraMissJu Blog'

[[module.imports]]
path = "github.com/CaiJimmy/hugo-theme-stack/v3"

[params.sidebar]
emoji = "🍥"
subtitle = "Mes expériences de tiramisu à Paris et ailleurs."
compact = true

[params.sidebar.avatar]
enabled = true
local = true
src = "img/tiravatar.jpg"

[params.DateFormat]
published = '02 January 2006'
lastUpdated = '02 January 2006 13:12'

[params.article.license]
enabled = true
default = 'Tous droits réservés'

[params.footer]
since = 2024
customText = "TiraMissJu Blog by JuliaLblnd"
